import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';

// Build the format modules to a temporary directory so this test never adds
// generated bytes to the repository. The original local-only files are read
// only; CI skips this real-data gate when they are absent.
const outDir = '/tmp/th08-web-formats';
execSync(
  'npx esbuild src/formats/ecl.ts src/formats/anm.ts src/formats/std.ts ' +
  `src/formats/msg.ts src/formats/sht.ts src/formats/rpy.ts ` +
  `--bundle --format=esm --outdir=${outDir} --out-extension:.js=.mjs --log-level=silent`
);
const { Ecl } = await import(`${outDir}/ecl.mjs`);
const { Anm, AnmRunner } = await import(`${outDir}/anm.mjs`);
const { Std } = await import(`${outDir}/std.mjs`);
const { Msg } = await import(`${outDir}/msg.mjs`);
const { Sht } = await import(`${outDir}/sht.mjs`);
const { Rpy } = await import(`${outDir}/rpy.mjs`);

const SAMPLES = 'reference/th08-original';
const sample = (name) => readFileSync(`${SAMPLES}/${name}`);
const hasSamples = [
  'ecldata1.ecl', 'title01.anm', 'stg1enm.anm', 'stage1.std',
  'msg1a.dat', 'ply00a.sht', 'ply00as.sht'
].every((name) => existsSync(`${SAMPLES}/${name}`)) && existsSync('replay/th8_udLy01.rpy');

test('TH08 ECL decodes the v3 container, timeline v2, and sub instructions', { skip: !hasSamples }, () => {
  const ecl = new Ecl(sample('ecldata1.ecl'));
  assert.equal(ecl.version, 8);
  assert.equal(ecl.subCount, 53);
  assert.equal(ecl.timelines.length, 2);
  assert.equal(ecl.subOffsets[0], 0x11c);
  assert.equal(ecl.view.u32(4 + 4), 0x9c18);

  const first = ecl.timeline[0];
  assert.deepEqual(
    ['time', 'arg0', 'op', 'size', 'rank', 'x', 'y', 'life', 'item', 'score'].map((key) => first[key]),
    [1, 14, 0, 0x20, 0xff, 30, -16, 20, -2, 1000]
  );

  const sub = ecl.sub(0);
  assert.deepEqual(
    ['time', 'id', 'size', 'rankMask', 'paramMask', 'args'].map((key) => sub[0][key]),
    [0, 0x37, 0x10, 0xff, 0, 0x128]
  );
  assert.equal(sub.at(-1).time, 5061);
  const sentinelOffset = 0x11c + sub.at(-1).offset + sub.at(-1).size;
  assert.equal(ecl.view.u32(sentinelOffset), 0xffffffff);
  assert.equal(ecl.view.u16(sentinelOffset + 4), 0xffff);
  // Raw opcodes stay stable for the engine layer: 0xa0 is the manager timer
  // setter and 0xa1 is the radius bullet clear.
  assert.ok(
    Array.from({ length: ecl.subCount }, (_, i) => ecl.sub(i))
      .some((instrs) => instrs.some((instr) => instr.id === 160))
  );
});

test('TH08 ANM entries use version 3 and executable v3 scripts', { skip: !hasSamples }, () => {
  const title = new Anm(sample('title01.anm'), 'title01');
  assert.equal(title.entries.length, 25);
  assert.ok(title.entries.every((entry) => entry.version === 3));
  assert.deepEqual({ ...title.sprites.get(0) }, {
    id: 0, x: 0, y: 0, w: 256, h: 480, imageKey: 'title02'
  });

  const enemy = new Anm(sample('stg1enm.anm'), 'stg1enm');
  assert.equal(enemy.entries.length, 1);
  assert.deepEqual(enemy.entries[0].scriptIds, [0, 1, 2, 3, 4, 5]);
  const runner = new AnmRunner(enemy, 2);
  assert.equal(runner.rect?.id, 5);
  assert.equal(runner.visible, true);
});

test('TH08 STD stage1 keeps the object/face/script layout intact', { skip: !hasSamples }, () => {
  const std = new Std(sample('stage1.std'));
  assert.equal(std.objectCount, 3);
  assert.equal(std.faceCount, 46);
  assert.equal(std.objects.length, 3);
  assert.equal(std.instances.length, 46);
  assert.equal(std.stageName, 'dm');
  assert.ok(std.objects.every((object) => object.quads.length > 0));
  std.advance();
  assert.ok(std.frame >= 0);
});

test('TH08 MSG decodes control args and XOR-0x77 Shift-JIS text', { skip: !hasSamples }, () => {
  const msg = new Msg(sample('msg1a.dat'));
  assert.equal(msg.isTh08, true);
  assert.equal(msg.messages.length, 2);
  const instrs = msg.messages[0];

  const interrupt = instrs.find((instr) => instr.op === 15);
  assert.deepEqual(interrupt.args, [0, 6, -1, -1, -1]);
  assert.equal(interrupt.slot, 0);
  assert.deepEqual(interrupt.interrupts, [6, -1, -1, -1]);

  assert.equal(instrs.find((instr) => instr.op === 16).text, 'ほら何も無いじゃないの！');
  assert.equal(instrs.find((instr) => instr.op === 3).text, 'って、さっきから何にも無いって……');
  assert.equal(instrs.find((instr) => instr.op === 8).text, '　闇に蠢く光の虫　');
  const slot = instrs.find((instr) => instr.op === 17);
  assert.deepEqual([slot.slot, slot.interrupt], [0, 7]);
});

test('TH08 SHT decodes the 56-byte header, records, unknowns, and callbacks', { skip: !hasSamples }, () => {
  const unfocused = new Sht(sample('ply00a.sht'));
  const focused = new Sht(sample('ply00as.sht'));
  for (const sht of [unfocused, focused]) {
    assert.equal(sht.isTh08, true);
    assert.deepEqual(sht.levels.map((level) => level.power), [8, 24, 48, 80, 128, 999]);
    assert.deepEqual(
      [sht.bombPerLife, sht.hitbox, sht.grazebox, sht.autocollectSpeed, sht.itemRadius, sht.pocLineY],
      [3, 1.649999976158142, 2.799999952316284, 10, 24, 128]
    );
    assert.deepEqual(
      [sht.unknownOld0, sht.unknownOld1, sht.unknownOld2],
      [18, 8000, 0.8999999761581421]
    );
  }
  assert.deepEqual(unfocused.levels.map((level) => level.shots.length), [1, 3, 3, 5, 5, 7]);
  assert.deepEqual(focused.levels.map((level) => level.shots.length), [2, 2, 3, 4, 5, 7]);

  const shot = unfocused.levels[0].shots[0];
  assert.deepEqual(
    ['interval', 'delay', 'x', 'y', 'hitboxW', 'hitboxH', 'angle', 'speed', 'damage', 'unknownOldSht0', 'orb']
      .map((key) => shot[key]),
    [5, 0, 0, 0, 18, 48, -1.5707963705062866, 16, 48, -50, 0]
  );
  assert.deepEqual(shot.funcs, [0, 0, 0, 0]);

  const angled = unfocused.levels[1].shots[1];
  assert.deepEqual(
    ['interval', 'x', 'y', 'hitboxW', 'hitboxH', 'angle', 'speed', 'damage', 'orb', 'unknownOldSht1', 'sprite']
      .map((key) => angled[key]),
    [15, 0, 0, 18, 18, -2.094395160675049, 10, 14, 0, 0, 2]
  );
  assert.equal(angled.unknownOldSht2, 1);
  assert.deepEqual(angled.funcs, [0, 1, 0, 0]);
});

test('TH08 T8RP decrypts, decompresses, and exposes wide stage records', { skip: !hasSamples }, () => {
  const rpy = new Rpy(readFileSync('replay/th8_udLy01.rpy'));
  assert.equal(rpy.version, 6);
  assert.equal(rpy.shotByte, 0);
  assert.equal(rpy.th08Character, 'reimuYukari');
  assert.equal(rpy.difficulty, 3);
  assert.equal(rpy.date, '11/11');
  assert.equal(rpy.name, 'Laggy');
  assert.equal(rpy.score, 156859787);

  assert.equal(rpy.image.u32(0x20), 0x134);
  assert.equal(rpy.image.u32(0x44), 0x32e32);
  const stage = rpy.stages[0];
  assert.equal(stage.stage, 1);
  assert.equal(stage.offset, 0x134);
  assert.equal(stage.rngSeed, 0x8fbe);
  // v6 stage blocks are {0x24-byte metadata, N x u16 input words} — 10504
  // frame records for stage 1 (cross-validated by the 352-byte slowdown
  // trailer: 1 lead byte + ceil(10504/30) = 351 bucket bytes).
  assert.equal(stage.inputs.length, 10504);
  assert.equal(stage.inputHigh.length, 0);
  assert.equal(stage.clockTime, 0);
  assert.deepEqual(
    ['score', 'pointItems', 'graze', 'pointItemExtends', 'nextPointItemExtendThreshold', 'pointItemValue', 'youkaiGauge', 'power', 'lives', 'bombs', 'rank', 'character']
      .map((key) => stage[key]),
    [0x708c8f, 0, 0, 0, 100, 300000, 0, 0, 6, 3, 8, 0]
  );
  assert.equal(stage.slowdown.length, Math.ceil(10504 / 30));
  assert.equal(stage.slowdown[0], 0x3c);
});
